services:
  - type: web
    name: phantomtg-keybot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      BOT_TOKEN: 8458741733:AAFEUhMaLJJdmDiyJ1cQgoNSlqXTxUCi6OA
      ADMIN_ID: 6895862356
